"
I can render a Ride presenter programmaticaly
"
Class {
	#name : #RideProgrammaticRenderer,
	#superclass : #RideRenderer,
	#category : #'Ride-Renderers'
}

{ #category : #rendering }
RideProgrammaticRenderer >> renderUsing: anAspectVariantSelector for: aRidePresenter [

	"Since it can have many, use anAspectVariantSelector 
	to decide in what aspect to render aRidePresenter."

	self notYetImplemented
]
